### ISSUE TITLE
Text node whitespace trimming before an html element

### ISSUE THREAD

**Issue by zbicin** [zaceno/hyperlit#10]
Hello

It seems there still is an issue with whitespaces when a text node is followed by an element, so this is related to #9 and #1 

Such a template:
```js
html`<p>I am <strong>strong</strong>!</p>`
```

Results in:
```html
<p>I am<strong>strong</strong>!</p>
```
without the whitespace between _am_ and `<strong>`.

I've tested it in htm and it works properly there, you can see a [Codepen demo here](https://codepen.io/zbicin/pen/XWdgeoM).

What do you think about this?

**Comment by zaceno** [comment]
Thanks for reporting @zbicin! I will look into this asap!

**Comment by zaceno** [comment]
Latest version (hyperlit@0.3.6, babel-plugin-hyperlit@0.1.5) should fix this issue @zbicin ! Thanks again for letting me know!
