### ISSUE TITLE
can't access property "is", t is undefined with components

### ISSUE THREAD

**Issue by v1rtl** [zaceno/hyperlit#13]
### The problem

When I try to mix HTML markup and components inside of one `html` string it breaks for some reason. Works fine when only one component, also breaks when there is more than one.

### Reproduction

code:

```js
import { app } from 'hyperapp'
import html from 'hyperlit'

const Table = ({ data }) => {

  return html`
  <table>
    <tr>
      <th>ID</th>
      <th>E-mail</th>
      <th>Balance</th>
      <th>Joined</th>
      <th>Status</th>
    </tr>
  </table>
  `
} 

app({
  init: { normal: [{
    id: 1,
    email: 'x@gmail.com',
    balance: '150',
    joined: '2020-09-14',
    status: 'unused',
  }], business: [{
    id: 1,
    email: 'x@gmail.com',
    balance: '150',
    joined: '2020-09-14',
    status: 'unused',
  },]},
  view: (state) => html`
  <${Table} data=${state.normal} />
  <h1>Business</h1>
  `,
  node: document.getElementById('app')
})
```

cdsbx: https://codesandbox.io/s/elastic-feistel-2utps

## Info

- `hyperapp`: 2.0.8
- `hyperlit`: 0.3.6

**Comment by zaceno** [comment]
This is not a hyperlit issue though, so nothing I can do about it. I’m afraid it’s just how hyperapp works. View must return a single vnode, not an array of two as your example has. If you would like to discuss this limitation I suggest you take it up in an issue/discussion at https://GitHub.com/jorgebucaran/hyperapp or join the Hyperapp slack
